version: '2'
networks:
  deluge:
    external:
      name: deluge_default
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: '1003'
      PGID: '1005'
      TZ: Europe/London
    networks:
      - default
      - deluge
    volumes:
    - /var/lib/docker/persistence/sonarr:/config
    - /var/lib/ds/tvshows:/tv
    - /var/lib/ds/torrent:/var/lib/ds/torrent
  oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    command:
      - http://sonarr:8989
