version: '2'
networks:
  deluge:
    external:
      name: deluge_default
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: '1003'
      PGID: '1005'
      TZ: Europe/London
    networks:
      - default
      - deluge
    volumes:
    - /var/lib/docker/persistence/sonarr:/config
    - /var/lib/ds/tvshows:/tv
    - /var/lib/ds/torrent:/var/lib/ds/torrent
  oauth:
    image: a5huynh/oauth2_proxy
    volumes:
    - /var/lib/docker/persistence/oauth:/config:ro
    tty: true
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    - VIRTUAL_PORT=80
    - SSL_POLICY=AWS-TLS-1-2-2017-01
    expose:
    - 80
    command:
    - -upstream=http://sonarr:8989
    - -config=/config/oauth2_proxy.cfg
