version: '2'
services:
  media-server:
    image: plexinc/pms-docker
    environment:
      TZ: Europe/London
      PLEX_UID: '1003'
      PLEX_GID: '1005'
    ports:
     - 32400:32400
    volumes:
    - /var/lib/plexmediaserver:/config
    - /var/lib/ds/transcode:/transcode
    - /var/lib/ds/movies:/var/lib/ds/movies
    - /var/lib/ds/tvshows:/var/lib/ds/tvshows
    - /var/lib/ds/music:/var/lib/ds/music
    tty: true
  plexpy:
    image: linuxserver/plexpy
    environment:
      TZ: Europe/London
      PUID: '1003'
      PGID: '1005'
    volumes:
    - /var/lib/docker/persistence/plexpy:/config
    - /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs:/logs:ro
    tty: true
  oauth:
    image: a5huynh/oauth2_proxy
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=80
    - ENABLE_ACME=true
    expose:
    - 80
    volumes:
    - /var/lib/docker/persistence/oauth:/config:ro
    tty: true
    command:
    - -upstream=http://plexpy:8181
    - -config=/config/oauth2_proxy.cfg
