version: '2'
networks:
  http:
    external: true
services:
  media-server:
    image: plexinc/pms-docker
    environment:
      TZ: Europe/London
      PLEX_UID: '1003'
      PLEX_GID: '1005'
    ports:
     - 32400:32400
    volumes:
    - /var/lib/plexmediaserver:/config
    - /var/lib/ds/transcode:/transcode
    - /var/lib/ds/transcode:/tmp
    - /var/lib/ds/movies:/var/lib/ds/movies
    - /var/lib/ds/tvshows:/var/lib/ds/tvshows
  tautulli:
    image: shiggins8/tautulli
    environment:
      TZ: Europe/London
      PUID: '1003'
      PGID: '1005'
    volumes:
    - /var/lib/docker/persistence/tautulli:/config
    - /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs:/logs:ro
    tty: true
  oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    command:
      - -upstream=http://tautulli:8181
      - -skip-auth-regex=^/image/|/newsletter/
