version: '2'

services:
  logstash:
    build: logstash
    image: mediastack/logstash
    depends_on:
      - elasticsearch
    ports:
      - 127.0.0.1:12201:12201/udp
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
      SERVER_NAME: ${VIRTUAL_HOST}
      ELASTICSEARCH_URL: http://elasticsearch:9200
  oauth:
    image: a5huynh/oauth2_proxy
    volumes:
    - /var/lib/docker/persistence/oauth:/config:ro
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    - VIRTUAL_PORT=80
    - SSL_POLICY=${SSL_POLICY}
    expose:
    - 80
    command:
    - -upstream=http://kibana:5601
    - -config=/config/oauth2_proxy.cfg

volumes:
  elasticsearch:
