version: '2'
networks:
  http:
    external: true
services:
  logstash:
    build: logstash
    image: mediastack/logstash
    depends_on:
      - elasticsearch
    ports:
      - 127.0.0.1:12201:12201/udp
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
      SERVER_NAME: ${VIRTUAL_HOST}
      ELASTICSEARCH_URL: http://elasticsearch:9200
  oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    logging:
      driver: 'json-file'
    command:
      - http://kibana:5601

volumes:
  elasticsearch:
