version: '2'
networks:
  torrent:
    external: true
  http:
    external: true
  emby:
    external: true
services:
  radarr:
    image: linuxserver/radarr
    restart: always
    environment:
      PUID: '1000'
      PGID: '1000'
    networks:
    - default
    - torrent
    - emby
    volumes:
    - /docker/radarr:/config
    - /ds/movies:/movies
    - /ds/torrent:/ds/torrent
    tty: true
  oauth:
    extends:
      file: ../oauth/docker-compose.yml
      service: oauth
    command:
      - http://radarr:7878
