version: '2'
networks:
  torrent:
    external: true
  http:
    external: true
services:
  radarr:
    image: linuxserver/radarr
    environment:
      PUID: '1003'
      PGID: '1005'
    networks:
    - default
    - torrent
    volumes:
    - /var/lib/docker/persistence/radarr:/config
    - /var/lib/ds/movies:/var/lib/ds/movies
    - /var/lib/ds/torrent:/var/lib/ds/torrent
    tty: true
  oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    command:
      - http://radarr:7878
