version: '2'
networks:
  deluge:
    external:
      name: deluge_default
services:
  radarr:
    image: linuxserver/radarr
    environment:
      PUID: '1003'
      PGID: '1005'
    networks:
    - default
    - deluge
    volumes:
    - /var/lib/docker/persistence/radarr:/config
    - /var/lib/ds/movies:/movies
    - /var/lib/ds/torrent:/var/lib/ds/torrent
    tty: true
  oauth:
    image: a5huynh/oauth2_proxy
    volumes:
    - /var/lib/docker/persistence/oauth:/config:ro
    tty: true
    expose:
    - 80
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    - VIRTUAL_PORT=80
    command:
    - -upstream=http://radarr:7878
    - -config=/config/oauth2_proxy.cfg
