version: '2'
networks:
  deluge:
    external:
      name: deluge_default
services:
  radarr:
    image: linuxserver/radarr
    environment:
      PUID: '1003'
      PGID: '1005'
    networks:
    - default
    - deluge
    volumes:
    - /var/lib/docker/persistence/radarr:/config
    - /var/lib/ds/movies:/movies
    - /var/lib/ds/torrent:/var/lib/ds/torrent
    tty: true
  oauth:
  oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    command:
      - http://radarr:7878
