version: '2'

services:
  traefik:
    image: traefik
    command: --api --docker -c /opt/traefik/traefik.toml
    networks:
      - http
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    environment:
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/opt/traefik

networks:
  http:
    external: true
