version: '2'
networks:
  deluge:
    external:
      name: deluge_default
services:
  jackett:
    image: linuxserver/jackett
    environment:
      TZ: Europe/London
    networks:
    - default
    - deluge
    volumes:
    - /var/lib/docker/persistence/jackett:/config
    tty: true
  oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    command:
      - http://jackett:9117
