version: '2'
networks:
  default:
    external:
      name: applications
services:
  jackett:
    image: linuxserver/jackett
    environment:
      TZ: Europe/London
    volumes:
    - /var/lib/docker/persistence/jackett:/config
    tty: true
