version: '2'
networks:
  deluge:
    external:
      name: deluge_default
services:
  jackett:
    image: linuxserver/jackett
    environment:
      TZ: Europe/London
    networks:
    - default
    - deluge
    volumes:
    - /var/lib/docker/persistence/jackett:/config
    tty: true
  oauth:
    image: a5huynh/oauth2_proxy
    volumes:
    - /var/lib/docker/persistence/oauth:/config:ro
    tty: true
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    - VIRTUAL_PORT=80
    - SSL_POLICY=${SSL_POLICY}
    expose:
    - 80
    command:
    - -upstream=http://jackett:9117
    - -config=/config/oauth2_proxy.cfg
