version: '2'
networks:
  default:
    external:
      name: applications
services:
  proxy:
    image: neilpang/nginx-proxy
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /var/lib/docker/persistence/proxy/certs:/etc/nginx/certs 
    - /var/lib/docker/persistence/proxy/acme-certs:/acmecerts
    tty: true
