version: '2'
networks:
  torrent:
    external: true
  http:
    external: true
services:
  vpn:
    image: dperson/openvpn-client
    tty: true
    restart: unless-stopped
    security_opt:
      - label:disable
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /dev/net:/dev/net:z
      - /var/lib/docker/persistence/vpn:/vpn
    command: -f 8112 -d
  deluge:
    image: linuxserver/deluge
    environment:
      PUID: '1003'
      PGID: '1005'
      TZ: Europe/London
      UMASK_SET: '002'
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
    - /var/lib/docker/persistence/deluge:/config
    - /var/lib/ds/torrent:/var/lib/ds/torrent
    tty: true
  deluge-api:
    image: dperson/nginx
    depends_on:
      - deluge
    links:
      - vpn:deluge
    networks:
      - default
      - torrent
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    tty: true
    command: -w "http://deluge:8112;/"
  jackett:
    image: linuxserver/jackett
    environment:
      TZ: Europe/London
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
    - /var/lib/docker/persistence/jackett:/config
    tty: true
  jackett-api:
    image: dperson/nginx
    depends_on:
      - jackett
    links:
      - vpn:jackett
    networks:
      - default
      - torrent
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    tty: true
    command: -w "http://jackett:9117;/"
  deluge-oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    labels:
      traefik.frontend.rule: "Host:${DELUGE_VIRTUAL_HOST}"
    command:
      - http://deluge-api:80
  jackett-oauth:
    extends:
      file: ../oauth/oauth-service.yml
      service: oauth
    labels:
      traefik.frontend.rule: "Host:${JACKETT_VIRTUAL_HOST}"
    command:
      - http://jackett-api:80
