version: '2'
networks:
  http:
    external: true
services:
  oauth:
    build: .
    image: mediastack/oauth
    tty: true
    volumes:
      - ./users:/config/users
    restart: on-failure
    networks:
      - default
      - http
    labels:
      traefik.enable: "true"
      traefik.port: "9000"
      traefik.docker.network: "http"
      traefik.frontend.rule: "Host:${VIRTUAL_HOST}"
    command:
    - -config=/config/oauth2_proxy.cfg
