version: '2'
services:
  oauth:
    build: .
    image: mediastack/oauth
    tty: true
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    - VIRTUAL_PORT=80
    - SSL_POLICY=${SSL_POLICY}
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    command:
    - -upstream=http://jackett:9117
    - -config=/config/oauth2_proxy.cfg
