version: '2'
services:
  oauth:
    build: .
    image: mediastack/oauth
    tty: true
    volumes:
      - ./users:/config/users
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    networks:
      - default
      - http
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${VIRTUAL_HOST}"
      traefik.docker.network: http
    command:
    - -config=/config/oauth2_proxy.cfg
