version: '2'
networks:
  http:
   external: true
services:
  minio:
    image: minio/minio
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp:{subdomain:.+}.${MINIO_DOMAIN},${MINIO_DOMAIN}"
      traefik.domain: ${MINIO_DOMAIN}
      traefik.port: "9000"
    environment:
    - MINIO_DOMAIN=${MINIO_DOMAIN}
    networks:
      - http
    volumes:
    - /var/lib/ds:/var/lib/ds
    - /var/lib/docker/persistence/minio:/root/.minio
    command: server /var/lib/ds
    tty: true
